### ISSUE TITLE
Does basic example work at all?

### ISSUE THREAD

**Issue by Terisback** [lus/dgc#10]
I see that only ping works (using basic.go example)
It is working? Then how to make it work.
![image](https://user-images.githubusercontent.com/26527529/85626292-4358fe00-b686-11ea-8477-d53b643aab42.png)

**Comment by lus** [comment]
Well, I think it should work, but I can't guarantee it for now. Currently I am planning to rewrite the whole thing to make it more efficient.

**Comment by Terisback** [comment]
Can you check it?

**Comment by kintar** [comment]
I can verify it does not.   The logic at router.go:111 (@master) creates a new slice of length `command.Aliases+1`, but  then proceeds to use append to add the aliases and command to it, which means we'll end up with a slice of size `command.Aliases*2+2`, with the first `command.Aliases+1` entries being a zero-value string.

I'll submit a PR in a minute.

**Comment by kintar** [comment]
@Lukaesebrot : PR submitted to fix this issue.

**Comment by Terisback** [comment]
Tnx, will check it
