### ISSUE TITLE
Add permission checks to Help command

### ISSUE THREAD

**Issue by yk-sgr** [lus/dgc#5]
Right now if the does not have enough permissions the whole bot just crashes.
I encountered this in my fork and implemented this [fix](https://github.com/DiscordStats/dgc/blob/a89f3bd086acf1fe190b69aea35aa5337de59ec6/help_command.go#L29).

**Comment by lus** [comment]
Hey^^
Yeah, I will fix that soon. Thanks for your issue.

**Comment by lus** [comment]
Alright. This is something with your fork since my version doesn't event handle errors in this case to prevent a bot crash. Because of that I don't think that would be necessary.
